export { Home } from "./Home/Home";
export { Intro } from "./Intro/Intro";
export { About } from "./About/About";
export { Goals } from "./Goals/Goals";
export { Header } from "./Header/Header";
export { Footer } from "./Footer/Footer";
export { Mission } from "./Mission/Mission";
export { Roadmap } from "./Roadmap/Roadmap";
export { Tokenomics } from "./Tokenomics/Tokenomics";
